/** API error codes (UPPER_SNAKE_CASE) for JSON responses and Google redirect query params. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMPLOYEE_CODE_TAKEN: 'EMPLOYEE_CODE_TAKEN',
  REGISTER_SESSION_EXPIRED: 'REGISTER_SESSION_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  GOOGLE_ONLY_ACCOUNT: 'GOOGLE_ONLY_ACCOUNT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  GOOGLE_PASSWORD_NOT_SUPPORTED: 'GOOGLE_PASSWORD_NOT_SUPPORTED',
  RESET_INVALID: 'RESET_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',

  GOOGLE_NOT_CONFIGURED: 'GOOGLE_NOT_CONFIGURED',
  GOOGLE_SIGN_IN_FAILED: 'GOOGLE_SIGN_IN_FAILED',
  GOOGLE_EMAIL_LINKED_OTHER_GOOGLE: 'GOOGLE_EMAIL_LINKED_OTHER_GOOGLE',
  GOOGLE_EMAIL_NOT_REGISTERED: 'GOOGLE_EMAIL_NOT_REGISTERED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
